### ISSUE TITLE
Persist the manifest output descriptor in  local file based or in memory cache

### ISSUE THREAD

**Issue by talwinder50** [trustbloc/adapter#579] opened 2022-01-25 17:12 UTC
Since it is passed everytime you start adapter, it should be in some kind of local file. based or in-memory cache.

https://github.com/trustbloc/adapter/pull/574/files#diff-df62cee2a182a885095fde997637fe846f0b95210d33652c59d298ff2f395f28R895

**Comment by rolsonquadras** [comment] 2022-02-22 17:51
This is a duplicate of https://github.com/trustbloc/adapter/issues/580

**Closed by rolsonquadras** 2022-02-22 17:51 UTC
Labels: waci
